FROM python:3.10-slim

WORKDIR /app

RUN apt-get update
RUN apt-get install default-jdk -y

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "consumer.py"]
